// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_HC0WPIWydNo42w7ptRP9dpg-zM4RV_M',
    appId: '1:1048743726139:web:2eee06e7bc97b017fee01e',
    messagingSenderId: '1048743726139',
    projectId: 'booktoplay-53718',
    authDomain: 'booktoplay-53718.firebaseapp.com',
    storageBucket: 'booktoplay-53718.firebasestorage.app',
    measurementId: 'G-2Z8YHPJW30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj6wCHyPLcLMfRMzY-HpvsUQmbc1XeiWc',
    appId: '1:1048743726139:android:da1b71ce648cfcb6fee01e',
    messagingSenderId: '1048743726139',
    projectId: 'booktoplay-53718',
    storageBucket: 'booktoplay-53718.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwxtxo3FB0ehfEj2hNMN0CKykaqwh55Zk',
    appId: '1:1048743726139:ios:c15635403cdc1f91fee01e',
    messagingSenderId: '1048743726139',
    projectId: 'booktoplay-53718',
    storageBucket: 'booktoplay-53718.firebasestorage.app',
    iosBundleId: 'com.example.book2playwebapp',
  );

}